version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app # Mount the project directory
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/video_data

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
